### PR TITLE
Change device scale factor

### LINKED ISSUE #348: Fix check failures on CRAN's M1 machine
## Email

> From: Prof Brian Ripley <[ripley@stats.ox.ac.uk](mailto:ripley@stats.ox.ac.uk)>
> Date: Tue, Aug 15, 2023 at 6:05 AM
> Subject: CRAN package shinytest2
> To: <[barret@posit.co](mailto:barret@posit.co)>
> CC: <[CRAN@r-project.org](mailto:CRAN@r-project.org)>
> 
> 
> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_shinytest2.html>.
> 
> Please correct before 2023-08-29 to safely retain your package on CRAN.
> 
> There is a check service for M1mac issues: see
> https://www.stats.ox.ac.uk/pub/bdr/M1mac/README.txt .
> However, it is running a much older version of the OS
> and toolchain -- and the latter often matters.
> 
> The CRAN Team

## CRAN Check Results

* Summary: http://web.archive.org/web/20230815130114/https://cran.r-project.org/web/checks/check_results_shinytest2.html
* Results: http://web.archive.org/web/20230815130349/https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/shinytest2-00check.html

```
checking tests ... [62s/73s] ERROR
  Running ‘spelling.R’ [0s/0s]
  Running ‘testthat.R’ [62s/73s]
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
   11. │ └─rlang:::signal_abort(cnd, .file)
   12. │ └─base::signalCondition(cnd)
   13. ├─shinytest2 (local) `<fn>`(`<rlng_rrr>`)
   14. │ └─shinytest2:::app_abort(...)
   15. │ └─rlang::abort(..., app = self, call = call)
   16. │ └─rlang:::signal_abort(cnd, .file)
   17. │ └─base::signalCondition(cnd)
   18. └─shinytest2 (local) `<fn>`(`<rlng_rrr>`)
   19. └─shinytest2:::app_abort(...)
   20. └─rlang::abort(..., app = self, call = call)
  
  [ FAIL 12 | WARN 0 | SKIP 6 | PASS 334 ]
  Error: Test failures
  [2023-08-15 05:46:09] [error] handle_read_frame error: websocketpp.transport:7 (End of File)
  Execution halted
```

<details>
<summary>Full check results</summary>

```
using R version 4.3.0 (2023-04-21)
using platform: x86_64-apple-darwin20 (64-bit)
R was compiled by
    Apple clang version 14.0.3 (clang-1403.0.22.14.1)
    GNU Fortran (GCC) 12.2.0
running under: macOS Ventura 13.3.1
using session charset: UTF-8
checking for file ‘shinytest2/DESCRIPTION’ ... OK
this is package ‘shinytest2’ version ‘0.3.0’
package encoding: UTF-8
checking package namespace information ... OK
checking package dependencies ... OK
checking if this is a source package ... OK
checking if there is a namespace ... OK
checking for executable files ... OK
checking for hidden files and directories ... OK
checking for portable file names ... OK
checking for sufficient/correct file permissions ... OK
checking whether package ‘shinytest2’ can be installed ... [7s/9s] OK
See the [install log](http://web.archive.org/web/20230815130349/https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/shinytest2-00install.html) for details.
used C++ compiler: ‘Apple clang version 14.0.3 (clang-1403.0.22.14.1)’
used SDK: ‘MacOSX11.3.sdk’
checking installed package size ... OK
checking package directory ... OK
checking ‘build’ directory ... OK
checking DESCRIPTION meta-information ... OK
checking top-level files ... OK
checking for left-over files ... OK
checking index information ... OK
checking package subdirectories ... OK
checking R files for non-ASCII characters ... OK
checking R files for syntax errors ... OK
checking whether the package can be loaded ... [0s/1s] OK
checking whether the package can be loaded with stated dependencies ... [0s/0s] OK
checking whether the package can be unloaded cleanly ... [0s/0s] OK
checking whether the namespace can be loaded with stated dependencies ... [0s/0s] OK
checking whether the namespace can be unloaded cleanly ... [0s/1s] OK
checking loading without being on the library search path ... [0s/1s] OK
checking dependencies in R code ... OK
checking S3 generic/method consistency ... OK
checking replacement functions ... OK
checking foreign function calls ... OK
checking R code for possible problems ... [5s/7s] OK
checking Rd files ... [0s/1s] OK
checking Rd metadata ... OK
checking Rd cross-references ... OK
checking for missing documentation entries ... OK
checking for code/documentation mismatches ... OK
checking Rd \usage sections ... OK
checking Rd contents ... OK
checking for unstated dependencies in examples ... OK
checking line endings in C/C++/Fortran sources/headers ... OK
checking compiled code ... OK
checking installed files from ‘inst/doc’ ... OK
checking files in ‘vignettes’ ... OK
checking examples ... [1s/2s] OK
checking for unstated dependencies in ‘tests’ ... OK
checking tests ... [62s/73s] ERROR
  Running ‘spelling.R’ [0s/0s]
  Running ‘testthat.R’ [62s/73s]
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
   11. │ └─rlang:::signal_abort(cnd, .file)
   12. │ └─base::signalCondition(cnd)
   13. ├─shinytest2 (local) `<fn>`(`<rlng_rrr>`)
   14. │ └─shinytest2:::app_abort(...)
   15. │ └─rlang::abort(..., app = self, call = call)
   16. │ └─rlang:::signal_abort(cnd, .file)
   17. │ └─base::signalCondition(cnd)
   18. └─shinytest2 (local) `<fn>`(`<rlng_rrr>`)
   19. └─shinytest2:::app_abort(...)
   20. └─rlang::abort(..., app = self, call = call)
  
  [ FAIL 12 | WARN 0 | SKIP 6 | PASS 334 ]
  Error: Test failures
  [2023-08-15 05:46:09] [error] handle_read_frame error: websocketpp.transport:7 (End of File)
  Execution halted
checking for unstated dependencies in vignettes ... OK
checking package vignettes in ‘inst/doc’ ... OK
checking running R code from vignettes ... [3s/3s] NONE
  ‘in-depth.Rmd’ using ‘UTF-8’... [0s/0s] OK
  ‘robust.Rmd’ using ‘UTF-8’... [0s/0s] OK
  ‘shinytest2.Rmd’ using ‘UTF-8’... [0s/0s] OK
  ‘use-application-audit.Rmd’ using ‘UTF-8’... [0s/0s] OK
  ‘use-ci.Rmd’ using ‘UTF-8’... [0s/0s] OK
  ‘use-package.Rmd’ using ‘UTF-8’... [0s/0s] OK
  ‘using-monkey-testing.Rmd’ using ‘UTF-8’... [0s/0s] OK
  ‘z-migration.Rmd’ using ‘UTF-8’... [0s/0s] OK
  ‘zzz-faq.Rmd’ using ‘UTF-8’... [0s/0s] OK
checking re-building of vignette outputs ... [23s/32s] OK
checking PDF version of manual ... [7s/10s] OK
DONE
Status: 1 ERROR
using check arguments '--no-clean-on-error '
```

</details>

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #348

FWIW, `deviceScaleFactor` was somewhat recently set to 1 https://github.com/rstudio/shinytest2/commit/563c24e38f96a91cf7bfa6e0d35264f9f1d7e435. That said, this commit message doesn't give much confidence that there was a real reason behind setting the default to 1 https://github.com/rstudio/shinytest2/pull/10/commits/34f733d9280e82a1cdbc29ceabbe82680c21a6ce

### CODE REVIEW

File: R/chromote-methods.R [hunk 1]
```diff
@@ -200,15 +200,15 @@ chromote_wait_for_condition <- function(
...
+chromote_set_device_metrics <- function(chromote_session, ..., width = NULL, height = NULL) {
   assert_chromote_session(chromote_session)
   ellipsis::check_dots_empty()
 
   chromote_session$Emulation$setDeviceMetricsOverride(
     width = width,
     height = height,
-    deviceScaleFactor = device_scale_factor,
-    mobile = mobile
+    deviceScaleFactor = 0,
```
Comment (cpsievert) [inline R/chromote-methods.R:210]: For reference https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride
